//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VariationOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_Cursach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees_Cursach()
        {
            this.Groups_Cursach = new HashSet<Groups_Cursach>();
            this.Users_Cursach = new HashSet<Users_Cursach>();
        }
    
        public int id_employee { get; set; }
        public string employee_name { get; set; }
        public int employee_age { get; set; }
        public int employee_id_specification { get; set; }
        public int employee_id_city { get; set; }
        public string employee_image { get; set; }
        public int employee_id_gender { get; set; }
        public int employee_id_department { get; set; }
        public string employee_personal_code { get; set; }
        public int employee_role { get; set; }
    
        public virtual Cities_Cursach Cities_Cursach { get; set; }
        public virtual Departments_Cursach Departments_Cursach { get; set; }
        public virtual Genders_Cursach Genders_Cursach { get; set; }
        public virtual Group_roles_Cursach Group_roles_Cursach { get; set; }
        public virtual Specifications_Cursach Specifications_Cursach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Groups_Cursach> Groups_Cursach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_Cursach> Users_Cursach { get; set; }
    }
}
