//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VariationOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups_Cursach
    {
        public int id_group { get; set; }
        public int group_id_employee { get; set; }
        public int group_id_role { get; set; }
        public int project_id { get; set; }
    
        public virtual Employees_Cursach Employees_Cursach { get; set; }
        public virtual Projects_Cursach Projects_Cursach { get; set; }
    }
}
