//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VariationOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects_Cursach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projects_Cursach()
        {
            this.Groups_Cursach = new HashSet<Groups_Cursach>();
        }
    
        public int id_project { get; set; }
        public string project_name { get; set; }
        public string project_number { get; set; }
        public int project_status { get; set; }
        public int customer_id { get; set; }
        public int user_creator_id { get; set; }
    
        public virtual Customers_Cursach Customers_Cursach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Groups_Cursach> Groups_Cursach { get; set; }
        public virtual Statuses_Cursach Statuses_Cursach { get; set; }
        public virtual Users_Cursach Users_Cursach { get; set; }
    }
}
