//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VariationOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Cursach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users_Cursach()
        {
            this.Projects_Cursach = new HashSet<Projects_Cursach>();
        }
    
        public int id_user { get; set; }
        public string user_login { get; set; }
        public string user_password { get; set; }
        public int user_id_role { get; set; }
        public int employee_id { get; set; }
    
        public virtual Employees_Cursach Employees_Cursach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projects_Cursach> Projects_Cursach { get; set; }
        public virtual User_role_Cursach User_role_Cursach { get; set; }
    }
}
